Traceback (most recent call last):
  File "/home/mmadeira/venvs/IPC-2021/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/mmadeira/venvs/IPC-2021/lib/python3.9/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/mmadeira/venvs/IPC-2021/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/mmadeira/venvs/IPC-2021/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/mmadeira/venvs/IPC-2021/lib/python3.9/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/home/mmadeira/venvs/IPC-2021/lib/python3.9/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/mmadeira/venvs/IPC-2021/lib/python3.9/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
""" Fun√ß√£o fatorial - teste √† instru√ß√£o try-except  """

import sys

def fatorial_r(n):
    """Calculo do fatorial de um n√∫mero.

    n! = n * (n-1)! para n > 1
    """

    assert type(n) is int, "n n√£o √© um inteiro: %r" % n
    assert n>0, "n n√£o √© maior que zero: %r" % n

    resultado = 1 # Elemento neutro da multiplica√ß√£o 
    if (n>1):
        resultado = n * fatorial_r(n-1)
    
    return resultado

def test_try_except():
    """Exemplo de uso de try-except"""

    while True:
        try:
            x = int(input('Insira um n√∫mero inteiro: '))
            z = fatorial_r(x)
            print('O fatorial de {} √© {}'.format(x,z))

        except KeyboardInterrupt:
            print('\n Terminado.')
            sys.exit(0)

        except ValueError:
            print('Tente novamente.')

        except EOFError:
            print('\n Fim dos dados. Terminado.')
            sys.exit(0)

if __name__ == '__main__':
    test_try_except()


------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mStdinNotImplementedError[0m                  Traceback (most recent call last)
[0;32m/tmp/ipykernel_349101/3165337542.py[0m in [0;36m<module>[0;34m[0m
[1;32m     39[0m [0;34m[0m[0m
[1;32m     40[0m [0;32mif[0m [0m__name__[0m [0;34m==[0m [0;34m'__main__'[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 41[0;31m     [0mtest_try_except[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     42[0m [0;34m[0m[0m

[0;32m/tmp/ipykernel_349101/3165337542.py[0m in [0;36mtest_try_except[0;34m()[0m
[1;32m     23[0m     [0;32mwhile[0m [0;32mTrue[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     24[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 25[0;31m             [0mx[0m [0;34m=[0m [0mint[0m[0;34m([0m[0minput[0m[0;34m([0m[0;34m'Insira um n√∫mero inteiro: '[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     26[0m             [0mz[0m [0;34m=[0m [0mfatorial_r[0m[0;34m([0m[0mx[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     27[0m             [0mprint[0m[0;34m([0m[0;34m'O fatorial de {} √© {}'[0m[0;34m.[0m[0mformat[0m[0;34m([0m[0mx[0m[0;34m,[0m[0mz[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/venvs/IPC-2021/lib/python3.9/site-packages/ipykernel/kernelbase.py[0m in [0;36mraw_input[0;34m(self, prompt)[0m
[1;32m   1039[0m         """
[1;32m   1040[0m         [0;32mif[0m [0;32mnot[0m [0mself[0m[0;34m.[0m[0m_allow_stdin[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1041[0;31m             raise StdinNotImplementedError(
[0m[1;32m   1042[0m                 [0;34m"raw_input was called, but this frontend does not support input requests."[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1043[0m             )

[0;31mStdinNotImplementedError[0m: raw_input was called, but this frontend does not support input requests.
StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.

